name: Build and Attest Docker Image

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      dockerfile:
        required: true
        type: string

jobs:
  build-and-attest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        id: push_image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ghcr.io/holo-routing/${{ inputs.image-name }}:latest

      - name: Attest image
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/holo-routing/${{ inputs.image-name }}
          subject-digest: ${{ steps.push_image.outputs.digest }}
          push-to-registry: true
